package enums;

public enum CoverageType {

    BAGGAGE_LOSS,
    BAGGAGE_DELAY,
    BAGGAGE_ASSISTANCE,

    PERSONAL_ACCIDENT,

    TRIP_DELAY,
    TRIP_CANCELLATION,
    MISSED_CONNECTION,
    DIVERTED_FLIGHT,

    FREE_DATE_CHANGE,
    ZERO_CANCELLATION,

    EMERGENCY_ASSISTANCE,
    TRAVEL_DOCUMENT_LOSS,
    MEDICAL_EMERGENCY
}
